### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by nilgradisnik** [nilgradisnik/coinprice-indicator#1]
High/low price alarm. Threshold should be configurable from the Preferences window.
Alarm should fire Ubuntu notification.

**Comment by sirajuddin97** [comment]
Need help with this?

**Comment by bluppfisk** [comment]
@sirajuddin97 I'd welcome any contributions to the project :)

**Comment by sirajuddin97** [comment]
I will give it a shot soon. :-)

**Comment by bluppfisk** [comment]
fixed in #37
