### ISSUE TITLE
AttributeError: 'Indicator' object has no attribute 'active_asset_pair'

### ISSUE THREAD

**Issue by zzks** [nilgradisnik/coinprice-indicator#15]
ubuntu14, "make install" was working, but "make" failed to start the application, error messages are: 

python3 coin/coin.py
INFO:root:Coin Price indicator v0.3.0
Traceback (most recent call last):
  File "coin/coin.py", line 140, in <module>
    coin = Coin()
  File "coin/coin.py", line 64, in __init__
    self.add_indicator()

  File "coin/coin.py", line 106, in add_indicator
    indicator.start()
  File "/home/sbai/Downloads/coinprice-indicator-master/coin/indicator.py", line 90, in start
    self._start_exchange()
  File "/home/sbai/Downloads/coinprice-indicator-master/coin/indicator.py", line 112, in _start_exchange
    home_currency = self.active_asset_pair.lower()[1:4]
AttributeError: 'Indicator' object has no attribute 'active_asset_pair'

**Comment by bluppfisk** [comment]
For me it works, but I already have settings for the app in dconf, so my results may be skewed. Have you tried starting it with `python3 coin/coin.py asset=kraken:XXBTZEUR:30` or any other asset?

**Comment by zzks** [comment]
@bluppfisk `python3 coin/coin.py asset=kraken:XXBTZEUR:30` works, THX a lot!

**Comment by bluppfisk** [comment]
@zzks cool; after this, just `make` should work too. But this reminds me I have to find out what is causing this.

**Comment by Drowze** [comment]
Same problem here. `kraken` seems to be working though.

With Kraken (working):
```
(master) [130] % python3 coin/coin.py asset=kraken:XXBTZUSD:30                                                                                                           ~/coinprice-indicator
INFO:root:Coin Price indicator v0.3.0
INFO:root:loading XXBTZUSD from kraken (30s)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.kraken.com

(coin.py:11636): libappindicator-WARNING **: Unable to register object on path '/org/ayatana/NotificationItem/Coin_Price_indicator': An object is already exported for the interface org.kde.StatusNotifierItem at /org/ayatana/NotificationItem/Coin_Price_indicator

(coin.py:11636): LIBDBUSMENU-GLIB-WARNING **: Unable to register object on bus: An object is already exported for the interface com.canonical.dbusmenu at /org/ayatana/NotificationItem/Coin_Price_indicator/Menu
```

With defaults (not working):
```
(master) [130] % python3 coin/coin.py
INFO:root:Coin Price indicator v0.3.0
Traceback (most recent call last):
  File "coin/coin.py", line 140, in <module>
    coin = Coin()
  File "coin/coin.py", line 64, in __init__
    self.add_indicator()
  File "coin/coin.py", line 106, in add_indicator
    indicator.start()
  File "/home/giba/coinprice-indicator/coin/indicator.py", line 90, in start
    self._start_exchange()
  File "/home/giba/coinprice-indicator/coin/indicator.py", line 112, in _start_exchange
    home_currency = self.active_asset_pair.lower()[1:4]
AttributeError: 'Indicator' object has no attribute 'active_asset_pair'
```

**Comment by eehlers** [comment]
i have the same error reported here.
then if i try to start it with 
python3 coin/coin.py asset=bistamp:XXBTZEUR:30
it fails with an error.
if i start it with kraken it seems to start OK.  if i try to change the exchange to bistamp it emits an error to stdout and stays on kraken.  after that if i change the refresh rate it also switches the currency from EUR to USD.

**Comment by bluppfisk** [comment]
happened when you used an uppercase letter, fixed now.  Also, bitstamp needs that 't' in there for it to work correctly.

**Comment by eehlers** [comment]
```
erik@laptop:git clone https://github.com/nilgradisnik/coinprice-indicator.git
Cloning into 'coinprice-indicator'...
remote: Counting objects: 466, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 466 (delta 51), reused 65 (delta 43), pack-reused 388
Receiving objects: 100% (466/466), 577.67 KiB | 647.00 KiB/s, done.
Resolving deltas: 100% (292/292), done.
erik@laptop:~/projects$ cd coinprice-indicator/
erik@laptop:~/projects/coinprice-indicator$ !1346
erik@laptop:python3 coin/coin.py asset=bitstamp:XXBTZEUR:30
Traceback (most recent call last):
  File "coin/coin.py", line 16, in <module>
    from indicator import Indicator
  File "/home/erik/projects/coinprice-indicator/coin/indicator.py", line 20, in <module>
    from exchange.gemini import Gemini
  File "/home/erik/projects/coinprice-indicator/coin/exchange/gemini.py", line 10, in <module>
    import grequests
ImportError: No module named 'grequests'

```

**Comment by bluppfisk** [comment]
my bad, I was experimenting with something and left a reference to grequests. Fixed now :)

**Comment by eehlers** [comment]
thank you :)

now when i do...

```
erik@laptop:~/projects/coinprice-indicator$ git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/nilgradisnik/coinprice-indicator
   436793c..73977f3  master     -> origin/master
Updating 436793c..73977f3
Fast-forward
 coin/exchange/gemini.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
erik@laptop:~/projects/coinprice-indicator$ python3 coin/coin.py asset=bitstamp:XXBTZEUR:30
INFO:root:Coin Price indicator v0.3.0
INFO:root:loading XXBTZEUR from bitstamp (30s)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.bitstamp.net
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.bitstamp.net
```

... it seems to start up successfully and i see the widget in the toolbar.  but it's on USD even though i said EUR at the command line.  and on the menu the only option is USD, no way to switch to EUR.

**Comment by bluppfisk** [comment]
Hi Eric

Bitstamp only offers USD-BTC rates, no EUR. Of course, the program should fail gracefully with an error, but we're not quite there yet :)
