### ISSUE TITLE
cant run on ubuntu 16

### ISSUE THREAD

**Issue by volandku** [nilgradisnik/coinprice-indicator#23]
python3 coin/coin.py file=startmany-btx.yaml
Traceback (most recent call last):
  File "coin/coin.py", line 5, in <module>
    import os, signal, yaml, sys, logging, gi
ModuleNotFoundError: No module named 'gi'

If i run as sudo - something works but i cant see in tray

**Comment by bluppfisk** [comment]
hi @volandku , you need to run `make install` first or at least install the python3 modules. Without the python modules, the app won't run.

**Comment by volandku** [comment]
Yes. I did it.
May be the reason is Py 3.6.3 Anaconda.
Also I tried 3.5 - but there was an error in **print url**  - missing parameter

**Comment by volandku** [comment]
`python3 coin/coin.py
Traceback (most recent call last):
  File "coin/coin.py", line 5, in <module>
    import os, signal, yaml, sys, logging, gi
  File "/home/sergey/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
`

**Comment by bluppfisk** [comment]
Hi Sergey, this is made for Python 3, won't work if you run it with a version of Python that requires different syntax.

**Comment by bluppfisk** [comment]
Also make sure you install dependencies with pip3, not pip as this might install dependencies for python2

**Comment by volandku** [comment]
Python 3.5 is not 3?
`python3.5 coin/coin.py 
Traceback (most recent call last):
  File "coin/coin.py", line 5, in <module>
    import os, signal, yaml, sys, logging, gi
  File "/usr/local/lib/python3.5/dist-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
`

**Comment by bluppfisk** [comment]
Sounds like the module you have is for the wrong version of Python. Try
installing or reinstalling for Python 3!

**Comment by bluppfisk** [comment]
closing as this seems beyond our power

**Comment by bluppfisk** [comment]
Hi @volandku you may want to try uninstalling the gi module (pip3 uninstall gi) and installing the python3 package through apt:

sudo apt install gir1.2-appindicator3-0.1

then launching again
