### ISSUE TITLE
Other coins disappear on the top bar

### ISSUE THREAD

**Issue by sirajuddin97** [nilgradisnik/coinprice-indicator#33]
Let's say I add four tickers: BTC, ETH, LTC and XRP. When I restart my PC or restart coinprice-indicator, all coin tickers disappear except the main one (BTC). I have to re-add the tickers every time I restart, why is that? I'm on Ubuntu 16.04 LTS by the way.

**Comment by bluppfisk** [comment]
@sirajuddin97 you can configure which tickers are loaded by editing startmany.yaml and then running the app with `make many` or `python3 coin/coin.py --file=startmany.yaml` that way it will always start the same tickers.

**Comment by sirajuddin97** [comment]
Oh.. I wasn't aware of that. Thanks @bluppfisk!
