### ISSUE TITLE
Where can I control the ticker label? 

### ISSUE THREAD

**Issue by DahmaniAdame** [nilgradisnik/coinprice-indicator#51]
I would like to have the pair after the price and the opposite and add a space too. 

Thanks!

**Comment by bluppfisk** [comment]
Hello Adame

Not sure what you mean.

The ticker label is set in different locations, currently, depending on user action. E.g. on line 77 of indicator.py, you'll find:

`self.indicator_widget.set_label(label, label)`

If you mean you're cloning and you want to permanently change how the label looks, I suggest you abstract this away in a function that also adds a space. I assume you're on GNOME3 where the icon lacks padding, and they stick together a bit?

As for the pair after the price: do you want to actually set the label to €6995 BTC-EUR ? You could do this in your own fork at the same locations where `self.indicator_widget.set_label()` is called. I won't do this in this fork as it would take up too much horizontal space.

I'm not sure what you mean by "the opposite"?

**Comment by bluppfisk** [comment]
closing after 1 week without further queries

**Comment by DahmaniAdame** [comment]
Sorry for the delay. 

Thanks for your replay. Was really useful.
